---
- name: Verify
  hosts: all
  become: true
  vars:
    goss_version: v0.3.16
    goss_arch: amd64
    goss_bin: /usr/local/bin/goss
    goss_test_directory: /tmp/molecule/goss
    goss_format: documentation
  tasks:
    - name: Include roles' meta data
      include_vars:
        file: "../../../meta/main.yml"
    - name: Test the distribution is supported. End the host if not.
      set_fact:
        supported_distributions: "{{ galaxy_info.platforms|json_query('[].name') }}"
    - block:
        - name: Ending play...
          meta: end_host
      when: ansible_distribution not in supported_distributions
    - name: Test the release is supported. End the host if not.
      set_fact:
        supported_releases: "{{ (galaxy_info.platforms| selectattr('name', 'match', ansible_distribution)| list|first).versions }}"
    - block:
        - name: Ending play...
          meta: end_host
      when: ansible_distribution_release not in supported_releases and ansible_distribution_major_version not in supported_releases

    - name: Install ca-certificates
      package:
        name: ca-certificates
        state: present

    - name: Download and install Goss
      get_url:
        url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
        dest: "{{ goss_bin }}"
        mode: 0755

    - name: Create Molecule directory for test files
      file:
        path: "{{ goss_test_directory }}"
        state: directory
        mode: '0755'

    - name: Find Goss tests on localhost
      find:
        paths: "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}"
        patterns:
          - "test[-.\\w]*.yml"
          - "test_host_{{ ansible_hostname }}[-.\\w]*.yml"
        excludes:
          - "test_host_(?!{{ ansible_hostname }})[-.\\w]*.yml"
        use_regex: true
      delegate_to: localhost
      register: test_files
      changed_when: false
      become: false

    - name: debug
      debug:
        msg: "{{ test_files.files }}"
        verbosity: 3

    - name: Copy Goss tests to remote
      copy:
        src: "{{ item.path }}"
        dest: "{{ goss_test_directory }}/{{ item.path | basename }}"
        mode: '0644'
      with_items:
        - "{{ test_files.files }}"

    - name: Register test files
      shell: "ls {{ goss_test_directory }}/test_*.yml"
      register: test_files
      changed_when: false

    - name: Execute Goss tests
      command: "{{ goss_bin }} -g {{ item }} validate --format {{ goss_format }}"
      register: test_results
      with_items: "{{ test_files.stdout_lines }}"
      failed_when: false
      changed_when: false

    - name: Display details about the Goss results
      debug:
        msg: "{{ item.stdout_lines }}"
      with_items: "{{ test_results.results }}"

    - name: Fail when tests fail
      fail:
        msg: "Goss failed to validate"
      when: item.rc != 0
      with_items: "{{ test_results.results }}"
