---
- name: Import check tasks
  import_tasks: check.yml

- name: add OS specific variables
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'main.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: vars_file

- name: Import install tasks
  import_tasks: install.yml
